os:
  - linux
addons:
  chrome: stable
language: node_js
node_js:
  - "6"
  - "8"
  - "10"
sudo: required
env:
  - TARGET=aarch64-unknown-linux-gnu
  - TYPESCRIPT=typescript@3.2.1
  - TYPESCRIPT=typescript@next
  - TYPESCRIPT=typescript@3.1.1
  - TYPESCRIPT=typescript@3.0.1
  - TYPESCRIPT=typescript@2.9.2
  - TYPESCRIPT=typescript@2.8.1
  - TYPESCRIPT=typescript@2.7.1
  - TYPESCRIPT=typescript@2.6.1
  - TYPESCRIPT=typescript@2.5.2
  - TYPESCRIPT=typescript@2.4.1
jobs:
    include:
         env: TARGET=aarch64-unknown-linux-gnu
         install:
           - uname -m
           - yarn install
           - yarn build
           - yarn lint
           - yarn add $TYPESCRIPT 
install:
   - uname -m
   - yarn install
   - yarn build
   - yarn lint
   - yarn add $TYPESCRIPT
